app = 'full-stack-open-phonebook-cold-forest-9220'
primary_region = 'arn'

[build]

[env]
  PORT = '3001'

[processes]
  app = "node index.js"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
